on:
  workflow_dispatch:
name: npm build Workflow


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: |
          npm install
          npm run build
