on:
  workflow_dispatch:
name: npm build Workflow


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          npm install
          npm run build
      - name: Show event trigger
        run: echo "Triggered by ${{ github.event_name }}"
