name: My First GitHub Actions Workflow

on:
  push:
    branches: [main]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print welcome message
        run: echo "🎉 Hello from GitHub Actions!"

      - name: Show current date and time
        run: date
