name: Java Maven Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: custom hellow action
        uses: shakeer405/customgiyhubactions@v1
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'   # Other options: adopt, zulu, corretto
          java-version: '17'        # Use 8, 11, or 17 depending on your project

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: ls; pwd; mvn install
      - name: sonar stage
        run:  mvn clean verify sonar:sonar -Dsonar.projectKey=usecase2 -Dsonar.host.url=http://148.100.79.130:9000 -Dsonar.login=sqp_c95eab6ff7550f2894b56bf5229df50ca3d8dc02
      - name: Archive JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-java-artifact
          path: target/*.jar
