name: Java Maven Build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'   # Other options: adopt, zulu, corretto
          java-version: '17'        # Use 8, 11, or 17 depending on your project

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn test
        working-directory: bank-ocr

      - name: Archive JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-java-artifact
          path: target/*.jar
